# Generated by Django 5.2.6 on 2025-09-25 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('episode_id', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('edited', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='core_film_title_efa29a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('diameter', models.CharField(blank=True, max_length=50, null=True)),
                ('climate', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('edited', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_planet_name_40650f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('mass', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('films', models.ManyToManyField(blank=True, related_name='characters', to='core.film')),
                ('homeworld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planet')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('average_height', models.CharField(blank=True, max_length=50, null=True)),
                ('average_lifespan', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('films', models.ManyToManyField(blank=True, related_name='species', to='core.film')),
                ('homeworld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planet')),
                ('people', models.ManyToManyField(blank=True, related_name='species_set', to='core.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.species'),
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('hyperdrive_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('crew', models.CharField(blank=True, max_length=50, null=True)),
                ('passengers', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('films', models.ManyToManyField(blank=True, related_name='starships', to='core.film')),
                ('pilots', models.ManyToManyField(blank=True, related_name='starships', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('crew', models.CharField(blank=True, max_length=50, null=True)),
                ('passengers', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('films', models.ManyToManyField(blank=True, related_name='vehicles', to='core.film')),
                ('pilots', models.ManyToManyField(blank=True, related_name='vehicles', to='core.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['name'], name='core_specie_name_fd9c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='core_person_name_ab6274_idx'),
        ),
        migrations.AddIndex(
            model_name='starship',
            index=models.Index(fields=['name'], name='core_starsh_name_679950_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['name'], name='core_vehicl_name_81f394_idx'),
        ),
    ]
