# Generated by Django 5.2.6 on 2025-09-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='film',
            name='core_film_title_efa29a_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='core_person_name_ab6274_idx',
        ),
        migrations.RemoveIndex(
            model_name='planet',
            name='core_planet_name_40650f_idx',
        ),
        migrations.RemoveIndex(
            model_name='species',
            name='core_specie_name_fd9c7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='starship',
            name='core_starsh_name_679950_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='core_vehicl_name_81f394_idx',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='starship',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='planet',
            name='climates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starship',
            name='manufacturers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacturers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planet',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='starship',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='starship',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['id'], name='core_film_id_846a63_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['id'], name='core_person_id_c797fc_idx'),
        ),
        migrations.AddIndex(
            model_name='planet',
            index=models.Index(fields=['id'], name='core_planet_id_682f55_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['id'], name='core_specie_id_62c576_idx'),
        ),
        migrations.AddIndex(
            model_name='starship',
            index=models.Index(fields=['id'], name='core_starsh_id_e8924b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['id'], name='core_vehicl_id_06b418_idx'),
        ),
    ]
